// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9nv4vNJkx6haVP4a54tL9bxXfxWscsxw',
    appId: '1:987695651068:web:36ac9a7260234449b4df79',
    messagingSenderId: '987695651068',
    projectId: 'nelson-firebase',
    authDomain: 'nelson-firebase.firebaseapp.com',
    storageBucket: 'nelson-firebase.appspot.com',
    measurementId: 'G-7LG2S67H8Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkSxIFEGczeYDsUxVKzWu_SvMqInbeAC0',
    appId: '1:987695651068:android:1c15f9673831fd26b4df79',
    messagingSenderId: '987695651068',
    projectId: 'nelson-firebase',
    storageBucket: 'nelson-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCa6KiQeZNbp9XgK_OLNm_4-m6VeKJbJ3I',
    appId: '1:987695651068:ios:5278a2ac3efddbbdb4df79',
    messagingSenderId: '987695651068',
    projectId: 'nelson-firebase',
    storageBucket: 'nelson-firebase.appspot.com',
    iosClientId: '987695651068-q83mlsk08td96n140iqsa523mcsq83qb.apps.googleusercontent.com',
    iosBundleId: 'com.nelson.nelsonFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCa6KiQeZNbp9XgK_OLNm_4-m6VeKJbJ3I',
    appId: '1:987695651068:ios:5278a2ac3efddbbdb4df79',
    messagingSenderId: '987695651068',
    projectId: 'nelson-firebase',
    storageBucket: 'nelson-firebase.appspot.com',
    iosClientId: '987695651068-q83mlsk08td96n140iqsa523mcsq83qb.apps.googleusercontent.com',
    iosBundleId: 'com.nelson.nelsonFirebase',
  );
}
